### ISSUE TITLE
Move repository

### ISSUE THREAD

**Issue by jteresco** [m18coppola/microMage#1]
Let's move this repository out of this organization.   Best choices are one of your own accounts, or if you really prefer it to be in one of the course organizations, to the SienaCSISAdvancedProgrammingS20 organization.

**Comment by jteresco** [comment]
Let's see if we can get this moved to one of your personal accounts.  Also, I am not seeing proposal.md in here so far.  @m18coppola @ShahHassan12 @DawsonB99 @mf12scan @nicolesell

**Comment by m18coppola** [comment]
Both issues rectified. Forgot to make the commit and close this issue. everything should be in line now.

**Comment by m18coppola** [comment]
@jteresco forgot to tag you for notification
